services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/laptop_shop?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      - mysql
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: on-failure
    ports:
      - "8081:80"
    depends_on:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./laptop_shop_data.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laptop_shop

volumes:
  mysql_data:
